### ISSUE TITLE
socketio.exceptions.BadNamespaceError

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#125]
When changing the detector from coins to plants the following Error occured. I changed the the 'wait_timeout' in the connect function of the [DetectorHardware](https://github.com/zauberzeug/rosys/blob/b66c9653e9aa9c68909bad4d5993405e962203c7/rosys/vision/detector_hardware.py#L15) in rosys from 3.0 to 10.0 which seems to fix the error.

```
rosys_1       | 2024-07-17 12:12:08.580 [ERROR] rosys/vision/detector_hardware.py:142: could not detect 32e4-9230-platform-3610000.xhci-usb-0:2.3:1.0/1721211128.5329092
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/app/rosys/vision/detector_hardware.py", line 114, in _detect
rosys_1       |     result: dict = await self.sio.call('detect', {
rosys_1       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/socketio/async_client.py", line 299, in call
rosys_1       |     await self.emit(event, data=data, namespace=namespace,
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/socketio/async_client.py", line 220, in emit
rosys_1       |     raise exceptions.BadNamespaceError(
rosys_1       | socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

**Comment by rodja** [comment]
The fix might be an coincidence. If you select the plant detector it may update to the latest available model on start. That would explain the connection errors...

**Comment by pascalzauberzeug** [comment]
We didn't see the error gain and updated the detector.
