### ISSUE TITLE
[U5 and F12] Detector - Can Not Write Request Body 

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#135]
The following Error occures when using the current detector version `0.1.1-nlv0.10.9-35.4.1`. Version `nlv0.10.8-35.4.1` is working and currently used on U5 and F12 instead of the newer version.
 
```
rosys_1       | 2024-07-17 17:22:30.862 [ERROR] rosys/rosys.py:162: error in "PlantLocator.__init__.<locals>.<lambda>"
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 627, in write_bytes
rosys_1       |     await self.body.write(writer)
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/payload.py", line 245, in write
rosys_1       |     await writer.write(self._value)
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 115, in write
rosys_1       |     self._write(chunk)
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
rosys_1       |     raise ConnectionResetError("Cannot write to closing transport")
rosys_1       | ConnectionResetError: Cannot write to closing transport
rosys_1       |
rosys_1       | The above exception was the direct cause of the following exception:
rosys_1       |
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/app/rosys/rosys.py", line 156, in _repeat
rosys_1       |     await invoke(self.handler)
rosys_1       |   File "/app/rosys/helpers/__init__.py", line 36, in invoke
rosys_1       |     result = await result
rosys_1       |              ^^^^^^^^^^^^
rosys_1       |   File "/app/field_friend/automations/plant_locator.py", line 153, in set_outbox_mode
rosys_1       |     async with aiohttp.request('PUT', url, data='continuous_upload' if value else 'stopped') as response:
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/client.py", line 1246, in __aenter__
rosys_1       |     self._resp = await self._coro
rosys_1       |                  ^^^^^^^^^^^^^^^^
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/client.py", line 608, in _request
rosys_1       |     await resp.start(conn)
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 976, in start
rosys_1       |     message, payload = await protocol.read()  # type: ignore[union-attr]
rosys_1       |                        ^^^^^^^^^^^^^^^^^^^^^
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/aiohttp/streams.py", line 640, in read
rosys_1       |     await self._waiter
rosys_1       | aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://localhost:8004/outbox_mode
```

**Comment by LukasBaecker** [comment]
Currently the error does not occure on F13.

**Comment by LukasBaecker** [comment]
I created a branch [detector_version_10_8](https://github.com/zauberzeug/field_friend/tree/detector_version_10_8) for those robots where the error occures

**Comment by rodja** [comment]
@NiklasNeugebauer as I understand it, it is an problem with the detector node itself. Am I correct? Can you link to an issue and give an estimated timeline? This is blocking our 0.2 release.

**Comment by NiklasNeugebauer** [comment]
I will work on it today, 10.8 is completely fine to use though.

**Comment by NiklasNeugebauer** [comment]
https://github.com/zauberzeug/learning_loop_node/pull/24

Can someone review this?
I'll build the container once it is merged and released.

**Comment by pascalzauberzeug** [comment]
I will close this.
Version `0.1.2-nlv0.10.10-35.4.1` is on main and was tested on U5. F12 needs to be updated.
